### ISSUE TITLE
Does a build include all of the crate's dependencies?

### ISSUE THREAD

**Issue by nataliepopescu** [rust-corpus/qrates#13]
Hello again! I am trying to count the number of calls to unsafe Rust functions per crate in the top 500 most downloaded crates on crates.io. I am currently just doing this by selecting user written unsafe const calls to Rust code: 

```
calls_unsafe_rust_funcs = unsafe_const_calls[
    unsafe_const_calls.abi == "Rust"
]
uw_calls_unsafe_rust_funcs = calls_unsafe_rust_funcs[
    calls_unsafe_rust_funcs.check_mode == "UnsafeBlockUserProvided"
]
values = uw_calls_unsafe_rust_funcs[['crate_callsite', 'package_version']].apply(
    lambda row: (row['crate_callsite'], row['package_version']), axis=1
).squeeze().value_counts()
```

One of the crates in `values` is "actix-web" (3.1.0), and after downloading it manually using the following command: 

```
wget www.crates.io/api/v1/crates/actix-web/3.1.0/download && tar -xzf download
```

we see that there are actually no "unsafe"s in the crate at all. Comparing that to the code from the "actix-web" github repo we find that there are many "unsafe"s in the "actix-http" crate, a dependency of "actix-web". This leads us to believe that your framework includes all dependencies of the crate in the final build, and that the "actix-web" result we got in `values` is actually due to "unsafe"s anywhere in its dependency chain. I've also noticed that the many ".bincode" files in the `workspace` dir for each crate (after successful compilation) correspond to the crates' dependencies, so I imagine the entire directory would be used for the queries. 

Is this understanding correct? And if so, do you know of a simple way we can limit the scope of the queries to just the top-level crate, excluding any dependencies? We are afraid that we are double counting many (if not all) of the unsafe uses because of this, and would ideally like to just report numbers on the top X crates themselves. 

Please let me know if you need any more information. Thank you!

**Comment by vakaras** [comment]
I tried to reproduce your setup as follows:

1.  Create `CrateList.json` with the following content:

    ```json
    {
      "creation_date": {
        "secs_since_epoch": 1579271281,
        "nanos_since_epoch": 847419904
      },
      "crates": [
        {
          "Package": {
            "name": "actix-web",
            "version": "3.1.0"
          }
        }
      ]
    }
    ```

2.  Follow the steps in the tutorial to get the query results.
3.  Use the following Notebook query to analyze the results:

    ```python
    import pandas as pd
    import utils
    unsafe_block_calls = utils.load_unsafe_block_calls_extended()
    print('expansion kinds:',
          unsafe_block_calls.query(
              'check_mode == "UnsafeBlockUserProvided"'
          )['unsafe_scope_expansion_kind'].value_counts())
    print('expansion kinds descriptions:',
          unsafe_block_calls.query(
              'check_mode == "UnsafeBlockUserProvided"'
          )['unsafe_scope_expansion_kind_descr'].value_counts())
    unsafe_block_calls.query('check_mode == "UnsafeBlockUserProvided"')[["file_name", "line", "col"]]
    ```

    Which prints:

    ```plain
    expansion kinds: MacroDerive    222
    Name: unsafe_scope_expansion_kind, dtype: int64
    expansion kinds descriptions: #[derive(::pin_project::__private::__PinProjectInternalDerive)]    222
    Name: unsafe_scope_expansion_kind_descr, dtype: int64

        file_name           line    col
    3   src/app_service.rs  133     0
    4   src/app_service.rs  133     0
    5   src/app_service.rs  133     0
    ...
    ```

So, we got that all expansion kinds are `MacroDerive` that are coming from `pin_project`. In other words, all unsafe code is generated by macros such as the following one from `src/app_service.rs` line 133:

```rust
#[pin_project::pin_project]
pub struct AppInitResult<T, B>
```

This can be quickly confirmed by grepping:
```bash
$ cargo download  -x   actix-web=3.1.0
$ cd actix-*
$ grep unsafe -nr src/ | wc -l
0
$ cargo expand | grep unsafe | wc -l
    Checking actix-web v3.3.0 (/tmp/bla/actix-web-3.3.0)
warning: 2 warnings emitted
    Finished check [unoptimized + debuginfo] target(s) in 0.70s

134
```

I guess your question is why `check_mode == "UnsafeBlockUserProvided"` does not filter out these cases? The reason is that `check_mode` filters out the unsafe code that is generated as an implementation detail of the Rust compiler. For example, if you have an `async` function, during the compilation some unsafe code will be emitted. However, I would argue that this unsafe code should not be taken into account when checking how unsafe is some library because the Rust compiler is anyway part of the trusted codebase. Since the `pin_project` macro is user-written, the unsafe code generated by it is counted towards user written unsafe. This approach, for example, allows catching things like [Plutonium](https://github.com/mxxo/plutonium).

**Comment by nataliepopescu** [comment]
Ah ok, yes that makes sense. So if the same macro is used in two different crates, each macro expansion is considered separately because by including the macro the user has effectively "written" that code (i.e. it is their responsibility). This is extremely helpful, thank you very much!
