### ISSUE TITLE
New Query: finding all #[cfg(target_feature = “some_val”)] annotations

### ISSUE THREAD

**Issue by nataliepopescu** [rust-corpus/qrates#5]
Hello! I am trying to search for all SIMD calls across some subset of crates.io and it seems like the #[cfg(target_feature = "some_val")] is a pretty good indication of this. Would such a query be possible to write with your framework? And if so, how would you write it? 

Thank you in advance!

**Comment by vakaras** [comment]
Our framework is using the intermediate representation of the compiler. As a result, things like `#[cfg(target_feature = "some_val")]` are already desugared and not visible to us. However, since `#[cfg(target_feature = "some_val")]` is a very syntactic feature, I think you can easily just grep for it. If you need more explanations on how to do that, please let me know.

By the way, in our framework, we have quite precise information about what function is going to be called at a specfic place (for static calls we know precise call targets). If the called SIMD functions are comming from a specific crate, then it should be quite easy to find all their callers.

**Comment by nataliepopescu** [comment]
Ah thats right, ok so if I instead would like to know of any calls coming from the std::arch module (which should be similar to how you queried for concurrency through compiler intrinsics, i.e. the std::intrinsics module) I would first have to compile a list of all the specific functions I would want to include in the query. Do you have a pointer to your implementation of this query or a similar one?

**Comment by vakaras** [comment]
If you want to know only the Rust packages that call SIMD intrinsics, something like this should work:

```python
import pandas as pd
import utils
const_calls_loaded = utils.load_const_calls()
const_calls_loaded.rename(
    columns={"crate_name": "crate_callsite", "crate": "crate_defsite"},
    inplace=True
)
simd_functions = set([
    x
    for x in const_calls_loaded.def_path.unique()
    if x.startswith('core[e667]::core_arch')
])
calls = const_calls_loaded[
    const_calls_loaded.def_path.isin(simd_functions)
]
calls
```
You can find the CSV file [here](https://pmserver.inf.ethz.ch/rust-corpus/simd_calls.csv).

If you want the precise line numbers of calls, then you will have to patch the extractor to collect that information. (It should be  straightforward to do; please let me know if you need some guidance.)

**Comment by vakaras** [comment]
> Edit: I would also be interested in any of the other query implementations for section 3.2 of this paper, if they are available. Thanks!

You can find the relevant Jupyter notebook [here](https://github.com/rust-corpus/qrates/blob/master/reports/RQ5.ipynb). (That folder contains all the notebooks used in that paper.)

**Comment by nataliepopescu** [comment]
Ohh I see I see, so most of the queries I would (probably) want to write would be in the format of the Jupyter notebook(s) you've linked. Under what circumstances would this not be enough? In other words, when would I need to add another query module [here](https://github.com/rust-corpus/qrates/tree/master/manager/src/queries)? Or do you anticipate that the current set of queries is sufficient for most/all searches?

**Comment by vakaras** [comment]
It depends on what you are looking for and how far that thing is from what we needed for our paper. It can happen that even a very simple thing (like #2) will not be supported if we did not need that for our paper.

**Comment by nataliepopescu** [comment]
Ah that makes sense. This should all be enough information to go off for now, thank you very much for your help!

**Comment by nataliepopescu** [comment]
Actually it looks like I closed this prematurely, as I have a couple more questions about your suggested implementation:

1. Why are you only loading const calls (isn't this a subset of all calls)?

2. Where does the 'core[e667]::core_arch' string come from? If I look at the MIR generated from Rust Playground [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dd0c11c70d5139f2cdf091e89aae3d3a), for instance, I only see 'std::arch' calls. Additionally, given the CSV you attached (presumably the result of running the query on all crates), I've confirmed that at least one of those crates does exist in the subset of crates.io that I'm running on yet I get no matches from running the query. I'm wondering if there's perhaps some local configuration that I'm missing?

**Comment by vakaras** [comment]
> Why are you only loading const calls (isn't this a subset of all calls)?

Yes, const calls are a subset of all calls, so we might miss some cases. More specifically, we will miss calls via function pointers because we cannot dermine a call target of a call via function pointer without a complex analysis. However, these calls seem to be super rare (<1% if I recall correctly), so should not cause a problem in practice.

> Where does the 'core[e667]::core_arch' string come from?

This string is part of the identifier used internally by the Rust compiler to identify definitions. `[e667]` is a hash of the crate that make the crate name unique; this is needed because Rust allows including multiple versions of the same crate as dependencies. The really painful thing is that the hash may change each time you recompile the project. Therefore, if you compile the same dataset and search for `core[e667]::core_arch` you may get no results because the `core` in your case may have gotten a different hash. To find out what hash was assigned to `core`, you need to manually look it up in the `builds` table.

> Additionally, given the CSV you attached (presumably the result of running the query on all crates), I've confirmed that at least one of those crates does exist in the subset of crates.io that I'm running on yet I get no matches from running the query. I'm wondering if there's perhaps some local configuration that I'm missing?

Could you say more precisely which query are you running? Are you trying to run the same query on your own dataset? If yes, then you need to check if hashes in your dataset match.

**Comment by nataliepopescu** [comment]
Aha! That fixed my problem. Yes I am running the same query on a more recent snapshot of crates.io (and only the top 500 most downloaded crates) and my core has a different hash. I got the hash from the `const_calls` table, is that what you meant by the `builds` table? Looks like I can get the hashes from any table with a `def_path` attribute, but is there a simpler way to do this?

**Comment by vakaras** [comment]
> Looks like I can get the hashes from any table with a `def_path` attribute

Yes, any table should work.

> but is there a simpler way to do this? by "simpler" I mean is there a dedicated table for getting the hashes.

Not really. The `builds` table has an entry per crate, so, in theory, is easier to work with, but at the same time, it has full hashes while the `def_path` includes only the first 4 symbols of it.
